import {getAll,put,remove,STORES} from './db.js';
const app=document.querySelector('#app');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=(p='id')=>`${p}-${crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2)}`;
async function currentYear(){const years=await getAll(STORES.schoolYears);return years.find(y=>y.isCurrent)||years.find(y=>!y.archived)||years.sort((a,b)=>String(b.id).localeCompare(String(a.id)))[0]}
async function currentRosterCount(){const year=await currentYear();if(!year)return 0;const enrollments=await getAll(STORES.enrollments);return new Set(enrollments.filter(e=>e.schoolYearId===year.id).map(e=>e.studentId)).size}
function chooseImage(){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.style.position='fixed';input.style.left='-9999px';document.body.appendChild(input);input.onchange=()=>{const f=input.files?.[0]||null;input.remove();resolve(f)};input.click()})}
function resizeImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2,c=document.createElement('canvas');c.width=640;c.height=640;c.getContext('2d').drawImage(img,sx,sy,side,side,0,0,640,640);resolve(c.toDataURL('image/jpeg',.86))};img.src=r.result};r.readAsDataURL(file)})}

export async function openSetup(){const year=await currentYear();if(!year)return;let pendingPhoto=null;app.innerHTML=`<section class="screen class-setup-screen"><header class="header"><button class="icon-btn" id="setup-back">←</button><div class="header-title"><small>Little Moments</small><h2>Set Up Your Class</h2></div><span class="header-scrapbook-accent">♡</span></header><div class="class-setup-intro"><h3>${esc(year.label)}</h3><p>Add your students once. Their names, profile photos, Moments, and yearly portfolios stay connected.</p></div><section class="class-setup-card"><div class="setup-photo-wrap"><button type="button" id="setup-photo" class="setup-photo"><span>＋</span><small>optional photo</small></button></div><label><span>Child's name</span><input id="setup-name" autocomplete="off" placeholder="Type a student's name"></label><button class="primary" id="setup-add">＋ Add Student</button><p id="setup-status">Start with one child, then keep adding ♡</p></section><section class="setup-roster"><div><h3>Current Class</h3><span id="setup-count">0 students</span></div><div id="setup-list"></div></section><button class="primary setup-done" id="setup-done">Done Setting Up ♡</button><div id="student-manager-root"></div></section>`;
const name=app.querySelector('#setup-name'),photoBtn=app.querySelector('#setup-photo'),status=app.querySelector('#setup-status'),list=app.querySelector('#setup-list'),count=app.querySelector('#setup-count'),managerRoot=app.querySelector('#student-manager-root');

async function draw(){const [students,enrollments]=await Promise.all([getAll(STORES.students),getAll(STORES.enrollments)]),ids=new Set(enrollments.filter(e=>e.schoolYearId===year.id).map(e=>e.studentId)),roster=students.filter(s=>ids.has(s.id)).sort((a,b)=>a.name.localeCompare(b.name));count.textContent=`${roster.length} ${roster.length===1?'student':'students'}`;list.innerHTML=roster.map(s=>`<button type="button" class="setup-student-row" data-manage-student="${esc(s.id)}"><div>${s.profilePhoto?`<img src="${esc(s.profilePhoto)}" alt="">`:`<span>${esc((s.name[0]||'?').toUpperCase())}</span>`}</div><strong>${esc(s.name)}</strong><b>Manage ›</b></button>`).join('')||'<p class="setup-empty">Your class list will appear here.</p>';list.querySelectorAll('[data-manage-student]').forEach(btn=>btn.onclick=()=>openStudentManager(roster.find(s=>s.id===btn.dataset.manageStudent)))}

function closeStudentManager(){managerRoot.innerHTML=''}
async function openStudentManager(student){if(!student)return;managerRoot.innerHTML=`<div class="student-manager-backdrop" id="student-manager-backdrop"><section class="student-manager-sheet" role="dialog" aria-modal="true" aria-label="Manage ${esc(student.name)}"><div class="student-manager-handle"></div><div class="student-manager-head"><div class="student-manager-photo">${student.profilePhoto?`<img src="${esc(student.profilePhoto)}" alt="">`:`<span>${esc((student.name[0]||'?').toUpperCase())}</span>`}</div><div><small>Manage Student</small><h3>${esc(student.name)}</h3></div><button type="button" id="student-manager-close" aria-label="Close">×</button></div><div class="student-manager-actions"><button type="button" class="student-action" id="student-edit-name"><span>✎</span><div><strong>Edit Name</strong><small>Fix spelling or update the child's name.</small></div><b>›</b></button><button type="button" class="student-action" id="student-change-photo"><span>▣</span><div><strong>Change Photo</strong><small>Choose a new profile picture.</small></div><b>›</b></button><button type="button" class="student-action remove-current" id="student-remove-current"><span>−</span><div><strong>Remove from Current Class</strong><small>Keeps past years, Moments, and portfolio history.</small></div><b>›</b></button><button type="button" class="student-action permanent-delete" id="student-delete-forever"><span>!</span><div><strong>Permanently Delete Student</strong><small>For accidental/test profiles only. This cannot be undone.</small></div><b>›</b></button></div><p class="student-manager-note">Removing from the current class is the safest choice when a child leaves your room. ♡</p></section></div>`;
const backdrop=managerRoot.querySelector('#student-manager-backdrop');managerRoot.querySelector('#student-manager-close').onclick=closeStudentManager;backdrop.onclick=e=>{if(e.target===backdrop)closeStudentManager()};
managerRoot.querySelector('#student-edit-name').onclick=async()=>{const next=prompt('Edit student name:',student.name);if(next===null)return;const clean=next.trim();if(!clean)return;student={...student,name:clean,updatedAt:new Date().toISOString()};await put(STORES.students,student);window.dispatchEvent(new Event('lm:data-changed'));closeStudentManager();status.textContent=`${clean} updated ♡`;await draw()};
managerRoot.querySelector('#student-change-photo').onclick=async()=>{const f=await chooseImage();if(!f)return;try{const profilePhoto=await resizeImage(f);student={...student,profilePhoto,updatedAt:new Date().toISOString()};await put(STORES.students,student);window.dispatchEvent(new Event('lm:data-changed'));closeStudentManager();status.textContent=`${student.name}'s photo updated ♡`;await draw()}catch{alert('That photo could not be prepared.')}};
managerRoot.querySelector('#student-remove-current').onclick=async()=>{if(!confirm(`Remove ${student.name} from the current class?\n\nTheir profile, past school years, Moments, and portfolio history will stay saved.`))return;const enrollments=await getAll(STORES.enrollments);const current=enrollments.filter(e=>e.studentId===student.id&&e.schoolYearId===year.id);for(const e of current)await remove(STORES.enrollments,e.id);window.dispatchEvent(new Event('lm:data-changed'));closeStudentManager();status.textContent=`${student.name} removed from the current class. Their history is still saved ♡`;await draw()};
managerRoot.querySelector('#student-delete-forever').onclick=async()=>{const typed=prompt(`Permanently delete ${student.name}?\n\nThis removes their profile, all school-year enrollments, and removes them from saved Moments. Moments that belong only to this child will also be deleted.\n\nType DELETE to continue.`,'');if(typed!=='DELETE')return;const [enrollments,moments]=await Promise.all([getAll(STORES.enrollments),getAll(STORES.moments)]);for(const e of enrollments.filter(e=>e.studentId===student.id))await remove(STORES.enrollments,e.id);for(const m of moments.filter(m=>Array.isArray(m.studentIds)&&m.studentIds.includes(student.id))){const remaining=m.studentIds.filter(id=>id!==student.id);if(remaining.length){await put(STORES.moments,{...m,studentIds:remaining,updatedAt:new Date().toISOString()})}else{await remove(STORES.moments,m.id);if(m.photoId)await remove(STORES.photos,m.photoId)}}await remove(STORES.students,student.id);window.dispatchEvent(new Event('lm:data-changed'));closeStudentManager();status.textContent=`${student.name} was permanently deleted.`;await draw()};
}

photoBtn.onclick=async()=>{const f=await chooseImage();if(!f)return;try{pendingPhoto=await resizeImage(f);photoBtn.innerHTML=`<img src="${pendingPhoto}" alt=""><small>change photo</small>`}catch{status.textContent='That photo could not be prepared.'}};
app.querySelector('#setup-add').onclick=async()=>{const childName=name.value.trim();if(!childName){status.textContent='Type the child’s name first ♡';name.focus();return}const students=await getAll(STORES.students),existing=students.find(s=>s.name?.trim().toLocaleLowerCase()===childName.toLocaleLowerCase());let student=existing;if(!student){student={id:uid('student'),name:childName,profilePhoto:pendingPhoto||null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put(STORES.students,student)}else if(pendingPhoto&&!student.profilePhoto){student={...student,profilePhoto:pendingPhoto,updatedAt:new Date().toISOString()};await put(STORES.students,student)}await put(STORES.enrollments,{id:`${student.id}__${year.id}`,studentId:student.id,schoolYearId:year.id,createdAt:new Date().toISOString()});window.dispatchEvent(new Event('lm:data-changed'));name.value='';pendingPhoto=null;photoBtn.innerHTML='<span>＋</span><small>optional photo</small>';status.textContent=`${childName} added ♡`;await draw();name.focus()};
app.querySelector('#setup-back').onclick=()=>location.reload();app.querySelector('#setup-done').onclick=()=>location.reload();await draw();name.focus()}

async function decorateHome(){const capture=app.querySelector('.capture-card');if(!capture)return;const n=await currentRosterCount(),existing=app.querySelector('.class-setup-prompt');if(n!==0){existing?.remove();return}if(existing)return;const prompt=document.createElement('section');prompt.className='card class-setup-prompt';prompt.innerHTML=`<div class="setup-heart">♡</div><div><h3>Set Up Your Class</h3><p>Add your students to start capturing Little Moments.</p></div><button class="primary" id="home-setup-class">＋ Add Students</button>`;capture.before(prompt);prompt.querySelector('#home-setup-class').onclick=openSetup}
window.__lmOpenClassSetup=openSetup;
new MutationObserver(()=>decorateHome().catch(console.error)).observe(app,{childList:true,subtree:true});
window.addEventListener('focus',()=>decorateHome().catch(console.error));
window.addEventListener('lm:data-changed',()=>decorateHome().catch(console.error));
decorateHome().catch(console.error);
