import {getAll,STORES} from './db.js';
const app=document.querySelector('#app');
const SAFETY_KEY='lm-data-safety-v1';
const RESTORE_FLAG='lm-restore-in-progress';
const REMINDER_DAYS=7,REMINDER_MOMENTS=10;
let checking=false,timer=null;
function readSafety(){try{return JSON.parse(localStorage.getItem(SAFETY_KEY)||'{}')}catch{return {}}}
function writeSafety(v){localStorage.setItem(SAFETY_KEY,JSON.stringify(v))}
async function counts(){const [students,moments,photos,enrollments]=await Promise.all([getAll(STORES.students),getAll(STORES.moments),getAll(STORES.photos),getAll(STORES.enrollments)]);return {students:students.length,moments:moments.length,photos:photos.length,enrollments:enrollments.length}}
function hasMeaningfulData(c){return c.students>0||c.moments>0||c.photos>0||c.enrollments>0}
function formatDate(v){if(!v)return'Never';try{return new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}catch{return'Never'}}
function backupDue(state,c){if(!hasMeaningfulData(c))return false;if(!state.lastConfirmedBackupAt)return true;const age=Date.now()-new Date(state.lastConfirmedBackupAt).getTime(),since=Math.max(0,c.moments-Number(state.momentsAtLastConfirmedBackup||0));return age>=REMINDER_DAYS*86400000||since>=REMINDER_MOMENTS}
function backupMessage(state,c){if(!hasMeaningfulData(c))return'Add classroom data before creating your first backup.';if(state.backupPreparedAt&&!state.lastConfirmedBackupAt)return'Backup file prepared, but not confirmed saved yet.';if(!state.lastConfirmedBackupAt)return'Backup recommended — you have classroom data with no confirmed second copy yet.';const since=Math.max(0,c.moments-Number(state.momentsAtLastConfirmedBackup||0)),days=Math.floor((Date.now()-new Date(state.lastConfirmedBackupAt).getTime())/86400000);if(since>=REMINDER_MOMENTS)return`Backup recommended — ${since} new Moments since your last confirmed backup.`;if(days>=REMINDER_DAYS)return`Backup recommended — last confirmed backup was ${days} days ago.`;return'Backup is up to date ✓'}
function removeWarning(){document.querySelector('.lm-data-warning')?.remove()}
function showWarning(state){if(document.querySelector('.lm-data-warning'))return;const old=state.lastKnown||{};const wrap=document.createElement('div');wrap.className='lm-data-warning';wrap.innerHTML=`<div class="lm-data-warning-card"><div class="lm-warning-heart">!</div><h2>Your saved classroom data is missing</h2><p>Little Moments previously saw <strong>${old.students||0} students</strong>, <strong>${old.moments||0} moments</strong>, and <strong>${old.photos||0} photos</strong> on this device, but the browser is currently reporting an empty database.</p><p><strong>Don't add a new class or restore over this yet.</strong> This warning is here so an unexpected empty database is never mistaken for a brand-new classroom.</p><div><button id="lm-data-retry" class="primary">Check Again</button><button id="lm-data-dismiss" class="secondary">Dismiss for Now</button></div></div>`;document.body.appendChild(wrap);wrap.querySelector('#lm-data-retry').onclick=()=>{removeWarning();checkHealth(true)};wrap.querySelector('#lm-data-dismiss').onclick=removeWarning}
async function checkHealth(force=false){if(checking||sessionStorage.getItem(RESTORE_FLAG)==='1')return;checking=true;try{const c=await counts(),state=readSafety(),meaningful=hasMeaningfulData(c);if(meaningful){state.hadData=true;state.lastKnown=c;state.lastSeenAt=new Date().toISOString();writeSafety(state);removeWarning()}else if(state.hadData&&hasMeaningfulData(state.lastKnown||{})){showWarning(state)}if(force||app.querySelector('.data-safety-card'))refreshCard(c)}catch(e){console.error('Little Moments data safety check failed',e)}finally{checking=false}}
async function persistenceInfo(){if(!navigator.storage?.persisted)return {supported:false,persisted:false};try{return {supported:true,persisted:await navigator.storage.persisted()}}catch{return {supported:true,persisted:false}}}
async function requestPersistence(){if(!navigator.storage?.persist)return false;try{return await navigator.storage.persist()}catch{return false}}
async function refreshCard(existingCounts=null){const card=app.querySelector('.data-safety-card');if(!card)return;const state=readSafety(),info=await persistenceInfo(),c=existingCounts||await counts(),backup=card.querySelector('#data-safety-backup'),protect=card.querySelector('#data-safety-protection'),button=card.querySelector('#protect-storage'),reminder=card.querySelector('#backup-reminder');if(backup)backup.textContent=state.lastConfirmedBackupAt?`Confirmed backup: ${formatDate(state.lastConfirmedBackupAt)}`:state.backupPreparedAt?`Prepared: ${formatDate(state.backupPreparedAt)} · not confirmed saved`:'No confirmed backup yet';if(protect)protect.textContent=!info.supported?'Storage protection is not supported in this browser.':info.persisted?'Protected storage is enabled on this device.':'Browser storage is not yet marked persistent.';if(button){button.textContent=info.persisted?'Storage Protected ✓':'Protect Storage';button.disabled=info.persisted}if(reminder){const due=backupDue(state,c);reminder.textContent=backupMessage(state,c);reminder.classList.toggle('backup-due',due);reminder.classList.toggle('backup-current',!due&&hasMeaningfulData(c))}}
function installCard(){const screen=app.querySelector('.settings-screen');if(!screen||screen.dataset.dataSafetyReady==='1')return;const list=screen.querySelector('.settings-list');if(!list)return;screen.dataset.dataSafetyReady='1';const card=document.createElement('section');card.className='settings-card data-safety-card';card.innerHTML=`<div class="settings-card-head"><div class="settings-card-icon">⚿</div><div><h3>Data Safety</h3><p>Extra protection for the classroom memories stored on this device.</p></div></div><div class="data-safety-lines"><div><span>Browser storage</span><strong id="data-safety-protection">Checking…</strong></div><div><span>Backup status</span><strong id="data-safety-backup">Checking…</strong></div></div><div class="backup-reminder" id="backup-reminder">Checking backup protection…</div><button type="button" class="secondary compact" id="protect-storage">Protect Storage</button><div class="settings-status"><span>Little Moments recommends a confirmed backup every 7 days or after 10 new Moments, whichever comes first.</span><span class="settings-pill">Safety</span></div>`;const backupCard=[...list.querySelectorAll('.settings-card')].find(x=>x.querySelector('h3')?.textContent.trim()==='Backup & Restore');if(backupCard)backupCard.insertAdjacentElement('beforebegin',card);else list.prepend(card);card.querySelector('#protect-storage').onclick=async()=>{const btn=card.querySelector('#protect-storage'),line=card.querySelector('#data-safety-protection');btn.disabled=true;btn.textContent='Protecting…';const ok=await requestPersistence();line.textContent=ok?'Protected storage is enabled on this device.':'This browser did not grant persistent storage. Keep using regular backups.';btn.textContent=ok?'Storage Protected ✓':'Try Again';btn.disabled=ok;const s=readSafety();s.persistenceRequestedAt=new Date().toISOString();s.persistenceGranted=ok;writeSafety(s)};refreshCard()}
async function notePrepared(){const s=readSafety();s.backupPreparedAt=new Date().toISOString();writeSafety(s);refreshCard()}
async function confirmSaved(){const s=readSafety(),c=await counts();s.lastConfirmedBackupAt=new Date().toISOString();s.momentsAtLastConfirmedBackup=c.moments;s.lastConfirmedBackupCounts=c;s.backupPreparedAt=null;delete s.lastBackupAt;delete s.momentsAtLastBackup;writeSafety(s);refreshCard(c)}
new MutationObserver(()=>installCard()).observe(app,{childList:true,subtree:true});
window.addEventListener('lm:data-changed',()=>{clearTimeout(timer);timer=setTimeout(()=>checkHealth(),250)});window.addEventListener('focus',()=>checkHealth());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkHealth()});
window.__lmBackupPrepared=notePrepared;window.__lmConfirmBackupSaved=confirmSaved;
installCard();setTimeout(()=>checkHealth(),700);
