import {replaceAllStoresAtomic,STORES} from './db.js';
const CACHE_NAME='little-moments-emergency-v1';
const CACHE_URL=new URL('./__little-moments-emergency/latest.json',location.href).toString();
let timer=null,busy=false;
function score(c={}){return (Number(c.moments)||0)*1000000+(Number(c.photos)||0)*10000+(Number(c.students)||0)*100+(Number(c.enrollments)||0)}
async function readMirror(){try{const cache=await caches.open(CACHE_NAME),r=await cache.match(CACHE_URL);if(!r)return null;const data=await r.json();return data?.format==='little-moments-backup'&&data?.stores?data:null}catch{return null}}
async function saveMirror(){if(busy||typeof window.__lmBuildFullBackup!=='function')return;busy=true;try{const data=await window.__lmBuildFullBackup();const c=data?.counts||{};if(!(c.students||c.moments||c.photos||c.enrollments))return;const existing=await readMirror();if(existing&&score(existing.counts)>score(c))return;const cache=await caches.open(CACHE_NAME);await cache.put(CACHE_URL,new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}));localStorage.setItem('lm-emergency-mirror-meta',JSON.stringify({createdAt:data.createdAt,counts:data.counts}));window.dispatchEvent(new Event('lm:emergency-mirror-saved'))}catch(e){console.error('Emergency mirror save failed',e)}finally{busy=false}}
function schedule(e){if(e?.detail?.operation==='atomic-restore')return;clearTimeout(timer);timer=setTimeout(saveMirror,2200)}
function revive(record){const out={...record};for(const[k,v]of Object.entries(out))if(v&&typeof v==='object'&&v.__lmBlob&&v.data){const[head,body]=String(v.data).split(','),mime=(head.match(/data:([^;]+)/)||[])[1]||'application/octet-stream',bin=atob(body||''),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);out[k]=new Blob([bytes],{type:mime})}return out}
async function restoreMirror(){const data=await readMirror();if(!data)throw new Error('No local emergency mirror was found.');const rows={};for(const name of Object.values(STORES))rows[name]=(Array.isArray(data.stores[name])?data.stores[name]:[]).map(revive);await replaceAllStoresAtomic(rows);return data}
window.addEventListener('lm:data-changed',schedule);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')saveMirror()});window.__lmReadEmergencyMirror=readMirror;window.__lmRestoreEmergencyMirror=restoreMirror;window.__lmSaveEmergencyMirror=saveMirror;setTimeout(saveMirror,3500);