const AUDIT_KEY='lm-db-destructive-audit-v1';
const SAFETY_KEY='lm-data-safety-v1';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')}catch{return fallback}}
async function cacheNames(){try{return await caches.keys()}catch{return[]}}
function navInfo(){try{const n=performance.getEntriesByType('navigation')[0];return n?{type:n.type,startTime:n.startTime,duration:Math.round(n.duration),transferSize:n.transferSize,encodedBodySize:n.encodedBodySize}:null}catch{return null}}
async function snapshot(){const audit=readJson(AUDIT_KEY,[]);const safety=readJson(SAFETY_KEY,{});let sw={supported:'serviceWorker'in navigator,controller:null,registration:null};try{sw.controller=navigator.serviceWorker?.controller?.scriptURL||null;const r=await navigator.serviceWorker?.getRegistration();sw.registration=r?{active:r.active?.scriptURL||null,waiting:r.waiting?.scriptURL||null,installing:r.installing?.scriptURL||null,scope:r.scope}:null}catch{}return{at:new Date().toISOString(),url:location.href,origin:location.origin,path:location.pathname,referrer:document.referrer||'',visibility:document.visibilityState,displayMode:matchMedia('(display-mode: standalone)').matches?'standalone':'browser',navigation:navInfo(),serviceWorker:sw,caches:await cacheNames(),audit:Array.isArray(audit)?audit:[],lastKnown:safety.lastKnown||null,lastSeenAt:safety.lastSeenAt||null}}
function formatAudit(a=[]){if(!a.length)return'<strong>No destructive-write audit entries exist.</strong><br><span>This means the current empty database was not recorded through clearStore() or replaceAllStoresAtomic() in db.js.</span>';return a.slice(0,12).map((x,i)=>`<div style="padding:8px 0;border-top:${i?'1px solid #dfd5ca':'0'}"><strong>${esc(x.operation||'unknown')}</strong> · ${esc(x.at||'unknown time')}<br>Store/reason: ${esc(x.store||x.reason||'—')}<br>Before: ${esc(JSON.stringify(x.before||{}))}<br>Incoming: ${esc(JSON.stringify(x.incoming||{}))}<details><summary>Call stack</summary><pre style="white-space:pre-wrap;font-size:9px">${esc(x.stack||'none')}</pre></details></div>`).join('')}
async function install(){const warning=document.querySelector('.lm-data-warning-card');if(!warning||warning.querySelector('#lm-forensic-panel'))return;const actions=warning.querySelector('.lm-warning-actions');if(!actions)return;const box=document.createElement('div');box.id='lm-forensic-panel';box.style.cssText='grid-column:1/-1;text-align:left;background:#fffaf2;border:1px solid #ddcfbf;border-radius:16px;padding:12px;font:11px/1.45 system-ui;color:#514a44;word-break:break-word';box.innerHTML='<strong>Forensic report</strong><br>Reading diagnostics only…';actions.insertBefore(box,actions.querySelector('#lm-data-fresh'));const d=await snapshot();box.innerHTML=`<strong style="font-size:13px">Forensic report · read only</strong><br><br><strong>Audit trail</strong><br>${formatAudit(d.audit)}<br><strong>Browser lifecycle</strong><br>URL: ${esc(d.url)}<br>Mode: ${esc(d.displayMode)} · Visibility: ${esc(d.visibility)}<br>Navigation: ${esc(JSON.stringify(d.navigation||{}))}<br>Service worker controller: ${esc(d.serviceWorker.controller||'none')}<br>Service worker registration: ${esc(JSON.stringify(d.serviceWorker.registration||{}))}<br>Caches: ${esc((d.caches||[]).join(', ')||'none')}<br>Previously remembered: ${esc(JSON.stringify(d.lastKnown||{}))}<br>Last seen: ${esc(d.lastSeenAt||'unknown')}<br><br><button id="lm-copy-forensic" class="secondary" style="width:100%">Copy Forensic Report</button>`;box.querySelector('#lm-copy-forensic').onclick=async()=>{const text=JSON.stringify(d,null,2);try{await navigator.clipboard.writeText(text);box.querySelector('#lm-copy-forensic').textContent='Copied ✓'}catch{box.querySelector('#lm-copy-forensic').textContent='Copy unavailable'}}}
new MutationObserver(()=>install().catch(()=>{})).observe(document.body,{childList:true,subtree:true});install().catch(()=>{});
