import {getAll,get,put,STORES} from './db.js';
const app=document.querySelector('#app');let urls=[];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const obj=blob=>{const u=URL.createObjectURL(blob);urls.push(u);return u};
const clear=()=>{urls.forEach(URL.revokeObjectURL);urls=[]};
function currentYearFrom(years){return years.find(y=>y.isCurrent)||years.find(y=>!y.archived)||years.sort((a,b)=>String(b.id).localeCompare(String(a.id)))[0]}
function sample(kind=0){const scenes=[['#dfe8da','#c97d6e'],['#f0dfd0','#9eb49a'],['#dce7e5','#d5a65d'],['#eaded8','#91a98e']];const [bg,accent]=scenes[kind%scenes.length];return `<div class="preview-scene" style="--scene-bg:${bg};--scene-accent:${accent}"><span></span><i></i><b></b></div>`}
function dateText(m){return m.createdAt?new Date(m.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):''}
async function mediaFor(m,index=0,preview=false){if(preview)return sample(index);const p=m.photoId?await get(STORES.photos,m.photoId):null;return p?.blob?`<img src="${obj(p.blob)}" alt="">`:sample(index)}
async function cardFor(m,index,preview=false){const media=await mediaFor(m,index,preview);return `<button class="journal-polaroid" data-open-moment="${esc(m.id)}"><div class="journal-photo">${media}</div><div class="journal-date">${esc(dateText(m))}</div><div class="journal-caption">${esc(m.caption||'a little moment ♡')}</div></button>`}
async function editMoment(m,preview=false,index=0,returnDetail=null){
  clear();let roster=[];
  if(preview){roster=[{id:'preview-child-1',name:'Avery'},{id:'preview-child-2',name:'Miles'},{id:'preview-child-3',name:'Sofia'},{id:'preview-child-4',name:'Theo'}];if(!Array.isArray(m.studentIds)||!m.studentIds.length)m.studentIds=['preview-child-1','preview-child-2'];}
  else{const [students,enrollments]=await Promise.all([getAll(STORES.students),getAll(STORES.enrollments)]);const rosterIds=new Set(enrollments.filter(e=>e.schoolYearId===m.schoolYearId).map(e=>e.studentId));roster=students.filter(s=>rosterIds.has(s.id)).sort((a,b)=>a.name.localeCompare(b.name));}
  const selected=new Set(m.studentIds||[]),story=m.caption||'';
  app.innerHTML=`<section class="screen moments-screen edit-moment-screen"><header class="header"><button class="icon-btn" id="edit-back">←</button><div class="header-title"><small>keep the memory, fix the details</small><h2>Edit Moment</h2></div><span style="width:44px"></span></header><div class="edit-moment-card"><label class="edit-label" for="edit-story">Little story</label><textarea id="edit-story" class="edit-story" maxlength="180">${esc(story)}</textarea><div class="edit-count"><span id="edit-count">${story.length}</span>/180</div><div class="edit-friends-head"><div><strong>Who’s in this moment?</strong><small>Tap names to add or remove.</small></div><span id="edit-selected-count">${selected.size} selected</span></div><div class="edit-friends-grid" id="edit-friends-grid">${roster.map(s=>`<button class="edit-friend ${selected.has(s.id)?'selected':''}" data-student="${esc(s.id)}">${esc(s.name)} <span>${selected.has(s.id)?'✓':'＋'}</span></button>`).join('')}</div><p class="edit-status" id="edit-status">${preview?'Preview mode · changes last until you leave this preview. ♡':'The photo stays exactly as it is. ♡'}</p><button class="primary" id="save-edit">Save Changes ♡</button></div></section>`;
  const textarea=app.querySelector('#edit-story'),count=app.querySelector('#edit-count'),status=app.querySelector('#edit-status');
  function syncFriends(){app.querySelector('#edit-selected-count').textContent=`${selected.size} selected`;app.querySelectorAll('[data-student]').forEach(btn=>{const on=selected.has(btn.dataset.student);btn.classList.toggle('selected',on);btn.querySelector('span').textContent=on?'✓':'＋'})}
  textarea.addEventListener('input',()=>count.textContent=textarea.value.length);app.querySelectorAll('[data-student]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.student;if(selected.has(id))selected.delete(id);else selected.add(id);syncFriends()}));
  app.querySelector('#edit-back').addEventListener('click',()=>showDetail(m,preview,index,returnDetail));
  app.querySelector('#save-edit').addEventListener('click',async()=>{const nextStory=textarea.value.trim();if(!nextStory){status.textContent='Add a little story before saving ♡';textarea.focus();return}if(!selected.size){status.textContent='Choose at least one child in this moment ♡';return}const btn=app.querySelector('#save-edit');btn.disabled=true;btn.textContent='Saving…';m.caption=nextStory;m.studentIds=[...selected];m.updatedAt=new Date().toISOString();if(!preview)await put(STORES.moments,m);showDetail(m,preview,index,returnDetail)});
}
async function showDetail(m,preview=false,index=0,returnDetail=null){
  clear();const media=await mediaFor(m,index,preview),favorite=!!m.favorite;
  app.innerHTML=`<section class="screen moments-screen detail-screen"><header class="header"><button class="icon-btn" id="detail-back">←</button><div class="header-title"><small>a page from our scrapbook</small><h2>Little Moment</h2></div><button class="icon-btn detail-heart ${favorite?'active':''}" id="detail-heart" aria-label="${favorite?'Remove from':'Add to'} favorites">${favorite?'♥':'♡'}</button></header><article class="detail-polaroid"><div class="detail-photo">${media}</div><div class="detail-date">${esc(dateText(m))}</div><h3>${esc(m.caption||'a little moment ♡')}</h3><p>${esc(m.note||m.story||'One of the little pieces of our year worth remembering. ♡')}</p><div class="detail-actions"><button class="detail-edit" id="detail-edit">✎ Edit Moment</button></div></article></section>`;
  app.querySelector('#detail-back').addEventListener('click',()=>returnDetail?document.dispatchEvent(new CustomEvent('lm:return-portfolio',{detail:returnDetail})):openMoments(preview));
  app.querySelector('#detail-heart').addEventListener('click',async()=>{m.favorite=!m.favorite;const b=app.querySelector('#detail-heart');b.classList.toggle('active',m.favorite);b.textContent=m.favorite?'♥':'♡';b.setAttribute('aria-label',m.favorite?'Remove from favorites':'Add to favorites');if(!preview)await put(STORES.moments,m)});
  app.querySelector('#detail-edit').addEventListener('click',()=>editMoment(m,preview,index,returnDetail));
}
async function openMoments(forcePreview=false){
  clear();const [moments,years]=await Promise.all([getAll(STORES.moments),getAll(STORES.schoolYears)]);const year=currentYearFrom(years);let base=moments.filter(m=>!year||m.schoolYearId===year.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),preview=false;
  if(forcePreview&&!base.length){preview=true;const now=Date.now();base=[{id:'preview-1',caption:'Building big ideas together ♡',createdAt:new Date(now).toISOString(),studentIds:['preview-child-1','preview-child-2']},{id:'preview-2',caption:'Colors, stories & creativity',createdAt:new Date(now-86400000).toISOString(),studentIds:['preview-child-2','preview-child-3']},{id:'preview-3',caption:'Scientist eyes at work',createdAt:new Date(now-172800000).toISOString(),studentIds:['preview-child-1']},{id:'preview-4',caption:'Learning with a friend',createdAt:new Date(now-259200000).toISOString(),studentIds:['preview-child-3','preview-child-4']}]}
  app.innerHTML=`<section class="screen moments-screen"><header class="header"><button class="icon-btn" id="moments-back">←</button><div class="header-title"><small>our little scrapbook</small><h2>Our Moments</h2></div><button class="icon-btn" id="header-favorites" aria-label="Show favorite moments">♡</button></header><div class="moments-intro"><p>the stories, discoveries &amp; everyday magic we've saved ♡</p></div><div class="moments-filters"><button class="moment-filter active" data-filter="all">All Moments</button><button class="moment-filter" data-filter="year">${esc(year?.label||'This Year')}</button><button class="moment-filter" data-filter="favorites">Favorites ♡</button></div><div class="moments-count" id="moments-count"></div><div id="moments-body"></div></section>`;
  const body=app.querySelector('#moments-body'),count=app.querySelector('#moments-count');
  async function renderFilter(filter='all'){let shown=base;if(filter==='favorites')shown=base.filter(m=>m.favorite);count.textContent=filter==='favorites'?`${shown.length} favorite ${shown.length===1?'moment':'moments'} ♡`:`${shown.length?`${shown.length} ${shown.length===1?'moment':'moments'} tucked inside`:'ready for your first memory'}`;if(!shown.length){body.innerHTML=filter==='favorites'?`<div class="favorites-empty"><div class="favorite-empty-heart">♡</div><h3>No favorites yet</h3><p>Tap the heart on a Little Moment to tuck it into this special collection.</p></div>`:`<div class="moments-empty"><div class="empty-stack"><div class="empty-sheet"></div><div class="empty-sheet"></div><div class="empty-sheet"></div></div><h3>Your journal is waiting</h3><p>Your first Little Moment will become the first page in this scrapbook.</p><button class="primary" id="empty-home">Back to Capture a Moment</button><button class="preview-link" id="preview-journal">Preview a filled journal →</button></div>`;app.querySelector('#empty-home')?.addEventListener('click',()=>location.reload());app.querySelector('#preview-journal')?.addEventListener('click',()=>openMoments(true));return}const cards=[];for(let i=0;i<shown.length;i++)cards.push(await cardFor(shown[i],i,preview));body.innerHTML=`<div class="moments-journal">${cards.join('')}</div>`;body.querySelectorAll('[data-open-moment]').forEach((b,i)=>b.addEventListener('click',()=>showDetail(shown[i],preview,i)))}
  function selectFilter(name){app.querySelectorAll('.moment-filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===name));renderFilter(name)}
  app.querySelector('#moments-back').addEventListener('click',()=>location.reload());app.querySelector('#header-favorites').addEventListener('click',()=>selectFilter('favorites'));app.querySelectorAll('.moment-filter').forEach(b=>b.addEventListener('click',()=>selectFilter(b.dataset.filter)));renderFilter('all');
}
document.addEventListener('lm:open-moment',e=>{const d=e.detail||{};if(d.moment)showDetail(d.moment,!!d.preview,d.index||0,d.returnDetail||null)});
document.addEventListener('click',e=>{const trigger=e.target.closest('#moments,#see-all');if(!trigger)return;e.preventDefault();e.stopImmediatePropagation();openMoments(false)},true);