import {getAll,get,STORES} from './db.js';
import {showDetail} from './moments-view.js?v=065';
const app=document.querySelector('#app');let urls=[];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const clear=()=>{urls.forEach(URL.revokeObjectURL);urls=[]};
const obj=blob=>{const u=URL.createObjectURL(blob);urls.push(u);return u};
function currentYearFrom(years){return years.find(y=>y.isCurrent)||years.find(y=>!y.archived)||years.sort((a,b)=>String(b.id).localeCompare(String(a.id)))[0]}
function initials(name='?'){return esc((name.trim()[0]||'?').toUpperCase())}
function avatar(student){if(student?.profilePhoto)return `<img src="${esc(student.profilePhoto)}" alt="">`;return `<span>${initials(student?.name)}</span>`}
function studentYears(studentId,enrollments,years){const ids=new Set(enrollments.filter(e=>e.studentId===studentId).map(e=>e.schoolYearId));return years.filter(y=>ids.has(y.id)).sort((a,b)=>String(b.id).localeCompare(String(a.id)))}
async function portfolioMomentCard(m,index){const p=m.photoId?await get(STORES.photos,m.photoId):null;const media=p?.blob?`<img src="${obj(p.blob)}" alt="">`:`<div class="portfolio-sample-art"><span></span><i></i><b></b></div>`;const date=m.createdAt?new Date(m.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';return `<button class="portfolio-memory" data-portfolio-moment="${esc(m.id)}" aria-label="Open ${esc(m.caption||'Little Moment')}"><div class="portfolio-memory-photo">${media}</div><div class="portfolio-memory-date">${esc(date)}</div><div class="portfolio-memory-caption">${esc(m.caption||'a little moment ♡')}</div></button>`}
async function openChildPortfolio(studentId,previewData=null,initialYear=null){clear();let students,enrollments,years,moments;if(previewData){({students,enrollments,years,moments}=previewData)}else{[students,enrollments,years,moments]=await Promise.all([getAll(STORES.students),getAll(STORES.enrollments),getAll(STORES.schoolYears),getAll(STORES.moments)])}const student=students.find(s=>s.id===studentId);if(!student)return openPortfolios();const yrs=studentYears(student.id,enrollments,years);let selectedYear=initialYear||yrs[0]?.id||currentYearFrom(years)?.id||'';
  app.innerHTML=`<section class="screen portfolio-screen child-portfolio"><header class="header"><button class="icon-btn" id="portfolio-child-back">←</button><div class="header-title"><small>their story, year by year</small><h2>${esc(student.name)}</h2></div><button class="icon-btn">♡</button></header><section class="child-hero"><div class="child-photo">${avatar(student)}</div><div><small>Little Moments Portfolio</small><h3>${esc(student.name)}</h3><p>${yrs.length} ${yrs.length===1?'school year':'school years'} saved ♡</p></div></section><div class="portfolio-year-tabs" id="portfolio-year-tabs">${yrs.map(y=>`<button class="portfolio-year-tab ${y.id===selectedYear?'active':''}" data-year="${esc(y.id)}">${esc(y.label)}</button>`).join('')}</div><div id="portfolio-year-body"></div></section>`;
  const body=app.querySelector('#portfolio-year-body');
  async function renderYear(yearId){selectedYear=yearId;app.querySelectorAll('.portfolio-year-tab').forEach(b=>b.classList.toggle('active',b.dataset.year===yearId));const year=years.find(y=>y.id===yearId);const list=moments.filter(m=>m.schoolYearId===yearId&&(m.studentIds||[]).includes(student.id)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));const favoriteCount=list.filter(m=>m.favorite).length;const cards=[];for(let i=0;i<list.length;i++)cards.push(await portfolioMomentCard(list[i],i));body.innerHTML=`<section class="portfolio-year-summary"><div><small>${esc(year?.label||'School Year')}</small><h3>${list.length} ${list.length===1?'memory':'memories'} collected</h3></div><span>${favoriteCount} favorite${favoriteCount===1?'':'s'} ♡</span></section>${list.length?`<div class="portfolio-memory-grid">${cards.join('')}</div>`:`<div class="portfolio-year-empty"><div class="portfolio-book-heart">♡</div><h3>This chapter is waiting</h3><p>Moments tagged with ${esc(student.name)} during ${esc(year?.label||'this year')} will collect here.</p></div>`}`;body.querySelectorAll('[data-portfolio-moment]').forEach((b,i)=>b.addEventListener('click',()=>showDetail(list[i],!!previewData,i,()=>openChildPortfolio(student.id,previewData,selectedYear))))}
  app.querySelector('#portfolio-child-back').addEventListener('click',()=>previewData?openPortfolios(true):openPortfolios(false));app.querySelectorAll('.portfolio-year-tab').forEach(b=>b.addEventListener('click',()=>renderYear(b.dataset.year)));renderYear(selectedYear);
}
function makePreview(){const now=new Date();const years=[{id:'2026-2027',label:'2026–2027',isCurrent:true},{id:'2025-2026',label:'2025–2026',archived:true}];const students=[{id:'preview-child',name:'Sample Friend'}];const enrollments=years.map(y=>({id:`preview-child__${y.id}`,studentId:'preview-child',schoolYearId:y.id}));const moments=[{id:'p1',schoolYearId:'2026-2027',studentIds:['preview-child'],caption:'Building big ideas together ♡',favorite:true,createdAt:now.toISOString()},{id:'p2',schoolYearId:'2026-2027',studentIds:['preview-child'],caption:'Painting our own story',createdAt:new Date(now-86400000).toISOString()},{id:'p3',schoolYearId:'2025-2026',studentIds:['preview-child'],caption:'A tiny scientist at work',favorite:true,createdAt:new Date(now-31536000000).toISOString()}];return {students,enrollments,years,moments}}
async function openPortfolios(forcePreview=false){clear();let students,enrollments,years,moments,preview=false;if(forcePreview){preview=true;({students,enrollments,years,moments}=makePreview())}else{[students,enrollments,years,moments]=await Promise.all([getAll(STORES.students),getAll(STORES.enrollments),getAll(STORES.schoolYears),getAll(STORES.moments)])}const current=currentYearFrom(years);const currentIds=new Set(enrollments.filter(e=>e.schoolYearId===current?.id).map(e=>e.studentId));const currentStudents=students.filter(s=>currentIds.has(s.id)).sort((a,b)=>a.name.localeCompare(b.name));const pastStudents=students.filter(s=>!currentIds.has(s.id)).sort((a,b)=>a.name.localeCompare(b.name));
  app.innerHTML=`<section class="screen portfolio-screen"><header class="header"><button class="icon-btn" id="portfolio-back">←</button><div class="header-title"><small>their stories, growing over time</small><h2>Portfolios</h2></div><button class="icon-btn">♡</button></header><div class="portfolio-intro"><p>one child · every year · all their little moments ♡</p></div><div class="portfolio-tabs"><button class="portfolio-tab active" data-view="current">Current Class</button><button class="portfolio-tab" data-view="past">Past Students</button></div><div class="portfolio-year-banner"><span>${esc(current?.label||'School Year')}</span><small>${currentStudents.length} ${currentStudents.length===1?'friend':'friends'} in this chapter</small></div><div id="portfolio-list"></div></section>`;
  const list=app.querySelector('#portfolio-list');
  function render(view='current'){const shown=view==='current'?currentStudents:pastStudents;if(!shown.length){list.innerHTML=`<div class="portfolio-empty"><div class="portfolio-empty-book">♡</div><h3>${view==='current'?'No portfolios yet':'No past students yet'}</h3><p>${view==='current'?'Add children to Current Class and their portfolios will begin here.':'When a child leaves the current class, their previous years stay safely here.'}</p>${view==='current'&&!preview?'<button class="preview-link" id="portfolio-preview">Preview a portfolio →</button>':''}</div>`;list.querySelector('#portfolio-preview')?.addEventListener('click',()=>openPortfolios(true));return}list.innerHTML=`<div class="portfolio-grid">${shown.map(s=>{const yrs=studentYears(s.id,enrollments,years);const count=moments.filter(m=>(m.studentIds||[]).includes(s.id)).length;return `<button class="portfolio-card" data-child="${esc(s.id)}"><div class="portfolio-card-photo">${avatar(s)}</div><div class="portfolio-card-copy"><h3>${esc(s.name)}</h3><p>${yrs.length} ${yrs.length===1?'school year':'school years'} saved</p><span>${count} ${count===1?'moment':'moments'} ♡</span></div><b>›</b></button>`}).join('')}</div>`;list.querySelectorAll('[data-child]').forEach(b=>b.addEventListener('click',()=>openChildPortfolio(b.dataset.child,preview?{students,enrollments,years,moments}:null)))}
  app.querySelector('#portfolio-back').addEventListener('click',()=>location.reload());app.querySelectorAll('.portfolio-tab').forEach(b=>b.addEventListener('click',()=>{app.querySelectorAll('.portfolio-tab').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.view)}));render('current');
}
document.addEventListener('click',e=>{const trigger=e.target.closest('#portfolios');if(!trigger)return;e.preventDefault();e.stopImmediatePropagation();openPortfolios(false)},true);