import {getAll,get,STORES} from './db.js';
const app=document.querySelector('#app');const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));let urls=[];const obj=b=>{const u=URL.createObjectURL(b);urls.push(u);return u};const fmt=d=>{if(!d)return'';const x=new Date(`${String(d).slice(0,10)}T12:00:00`);return x.toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})};const BG=['A','B','C','D'];const PREF_KEY='lm-preferences-v1';const THEMES={
'early-eagle':{name:'Early Eagle Classic',cover:'early-eagle-cover',page:'early-eagle-bg',coverImage:'Early_Eagle_Classic_Cover.png',pageImage:bg=>`Early_Eagle_Classic_Background_${bg}.png`,schoolName:false},
'woodland-neutral':{name:'Woodland Neutral',cover:'woodland-neutral-cover',page:'woodland-neutral-bg',coverImage:'Woodland_Neutral_Cover.png',pageImage:bg=>`Woodland_Neutral_Background_${bg}.png`,schoolName:true},
'colorful-classroom':{name:'Colorful Classroom',cover:'colorful-classroom-cover',page:'colorful-classroom-bg',coverImage:'Colorful_Classroom_Cover.png',pageImage:bg=>`Colorful_Classroom_Background_${bg}.png`,schoolName:true},
'make-it-yours':{name:'Make It Yours',cover:'make-it-yours-cover',page:'make-it-yours-bg',coverImage:'Make_It_Yours_Cover.png',pageImage:null,schoolName:true}
};function preferences(){try{return JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{return {}}}
function hexRgb(hex){const h=String(hex||'').replace('#','');if(!/^[0-9a-f]{6}$/i.test(h))return {r:90,g:105,b:120};return {r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)}}
function rgbHex({r,g,b}){return '#'+[r,g,b].map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('')}
function mix(a,b,t){const x=hexRgb(a),y=hexRgb(b);return rgbHex({r:x.r+(y.r-x.r)*t,g:x.g+(y.g-x.g)*t,b:x.b+(y.b-x.b)*t})}
function soften(hex){const c=hexRgb(hex),max=Math.max(c.r,c.g,c.b),min=Math.min(c.r,c.g,c.b),avg=(c.r+c.g+c.b)/3,sat=max-min,f= sat>150?.34:sat>95?.25:.16;return mix(hex,rgbHex({r:avg,g:avg,b:avg}),f)}
function palette(hex){const medium=soften(hex);return {dark:mix(medium,'#403c38',.43),medium:mix(medium,'#f5efe5',.12),soft:mix(medium,'#f8f1e7',.48),wash:mix(medium,'#fffaf2',.68)}}
const pageArt=src=>src?`<img class="print-page-art" src="./${esc(src)}" alt="" aria-hidden="true">`:'';
const customArt=()=>`${pageArt('Make_It_Yours_Cover.png')}<svg class="miy-color-art" viewBox="0 0 850 1100" preserveAspectRatio="none" aria-hidden="true"><g class="miy-main miy-doodles"><path d="M72 284 C52 261 35 291 72 320 C109 291 92 261 72 284Z"/><path d="M108 790 C93 774 81 793 108 815 C136 793 124 774 108 790Z"/><circle cx="82" cy="240" r="5"/><circle cx="67" cy="331" r="4"/><path class="miy-line" d="M61 655 q-16 18 3 31 q18 12 1 28 q-13 12 2 26"/></g><g class="miy-accent miy-tape"><rect x="42" y="34" width="138" height="24" rx="6" transform="rotate(-7 42 34)"/><rect x="674" y="1014" width="116" height="22" rx="6" transform="rotate(-6 674 1014)"/></g><g class="miy-accent miy-doodles"><path d="M708 700 C693 683 680 703 708 726 C736 703 723 683 708 700Z"/><path d="M126 946 C114 932 103 949 126 968 C150 949 139 932 126 946Z"/><circle cx="770" cy="108" r="6"/><circle cx="744" cy="752" r="4"/><path class="miy-line" d="M760 542 q15 11 2 24 q-12 12 3 24 q12 10 -1 22"/></g></svg>`;
async function card(m){const p=m.photoId?await get(STORES.photos,m.photoId):null,media=p?.blob?`<img src="${obj(p.blob)}" alt="">`:'<div class="print-photo-empty">♡</div>',tags=(m.tags||[]).map(t=>`<span>${esc(t)}</span>`).join(''),date=fmt(m.date||m.createdAt);return `<section class="print-mini-memory"><div class="mini-date">${esc(date)}</div><div class="mini-polaroid-print"><div class="mini-photo-print">${media}</div></div><h3>${esc(m.caption||'A little moment ♡')}</h3>${tags?`<div class="mini-tags">${tags}</div>`:''}</section>`}
async function openPrintPreview(studentId,yearId){urls.forEach(URL.revokeObjectURL);urls=[];const pref=preferences(),themeId=THEMES[pref.portfolioTheme]?pref.portfolioTheme:'early-eagle',theme=THEMES[themeId],schoolName=String(pref.schoolName||'').trim(),mainRaw=pref.makeItYoursMain||'#173b66',accentRaw=pref.makeItYoursAccent||'#d5a128',mp=palette(mainRaw),ap=palette(accentRaw),vars=`--miy-main:${mp.medium};--miy-main-dark:${mp.dark};--miy-main-soft:${mp.soft};--miy-main-wash:${mp.wash};--miy-accent:${ap.medium};--miy-accent-dark:${ap.dark};--miy-accent-soft:${ap.soft};--miy-accent-wash:${ap.wash}`;const [students,years,moments]=await Promise.all([getAll(STORES.students),getAll(STORES.schoolYears),getAll(STORES.moments)]),student=students.find(s=>s.id===studentId),year=years.find(y=>y.id===yearId);if(!student||!year)return;const list=moments.filter(m=>m.schoolYearId===yearId&&(m.studentIds||[]).includes(studentId)).sort((a,b)=>new Date(a.date||a.createdAt)-new Date(b.date||b.createdAt)),pages=[];const art=themeId==='make-it-yours'?customArt():pageArt(theme.coverImage);pages.push(`<article class="print-page print-cover ${theme.cover} theme-${themeId}" style="${themeId==='make-it-yours'?vars:''}">${art}<div class="cover-content"><h1><em>${esc(student.name)}’s</em><br>Little Moments</h1><div class="cover-year">${esc(year.label)}</div><div class="print-cover-photo">${student.profilePhoto?`<img src="${esc(student.profilePhoto)}" alt="">`:`<span>${esc((student.name[0]||'?').toUpperCase())}</span>`}</div><p>Our year, one moment at a time. ♡</p>${theme.schoolName&&schoolName?`<div class="cover-school-name">${esc(schoolName)}</div>`:''}</div></article>`);let pageIndex=0;for(let start=0;start<list.length;start+=4){const chunk=list.slice(start,start+4),cards=[];for(const m of chunk)cards.push(await card(m));const bg=BG[pageIndex%BG.length];pages.push(`<article class="print-page print-grid-page ${theme.page} bg-${bg} theme-${themeId}" style="${themeId==='make-it-yours'?vars:''}">${pageArt(theme.pageImage?theme.pageImage(bg):null)}<div class="page-label">Little Moments · ${esc(year.label)}</div><div class="print-four-grid count-${chunk.length}">${cards.join('')}</div></article>`);pageIndex++}app.innerHTML=`<section class="print-preview-screen theme-preview-${themeId}" style="${themeId==='make-it-yours'?vars:''}"><div class="print-preview-toolbar"><button id="print-back">← Back</button><div><strong>${esc(theme.name)}</strong><small>${esc(student.name)} · ${esc(year.label)} · ${list.length} ${list.length===1?'moment':'moments'} · 4 per page</small></div><button id="print-now">Print / Save PDF</button></div><div class="print-pages">${pages.join('')}</div></section>`;app.querySelector('#print-back').onclick=()=>location.reload();app.querySelector('#print-now').onclick=()=>window.print();window.scrollTo({top:0,behavior:'instant'})}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-print-portfolio]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openPrintPreview(btn.dataset.student,btn.dataset.year)},true);
