import {getAll,put,remove,STORES,ensureInitialSchoolYear} from './db.js';
const app=document.querySelector('#app');
const SID='lm-demo-avery';
const CAPTIONS=['Building a tall tower','Painting with watercolors','Exploring at the light table','Making a playdough creation','Reading with a friend','Investigating leaves','Writing my name','Building a bridge','Pretend cooking together','Sorting colorful counters','Creating with loose parts','Dancing to our favorite song','Drawing a family picture','Exploring ramps and cars','Retelling a favorite story','Working on a puzzle'];
const TAGS=[['Blocks'],['Art'],['Discovery'],['Playdough'],['Library'],['Science'],['Writing'],['Blocks'],['Dramatic Play'],['Math'],['Art'],['Music'],['Writing'],['Science'],['Literacy'],['Thinking']];
function svgPhoto(i){const palettes=[['#d9e9f2','#7ca5b8'],['#f3dfd2','#c78970'],['#e3ead6','#8ba276'],['#e8def0','#9a7dad']];const [bg,accent]=palettes[i%palettes.length],label=CAPTIONS[i].split(' ').slice(0,2).join(' ');return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="700" viewBox="0 0 900 700"><rect width="900" height="700" fill="${bg}"/><circle cx="450" cy="260" r="105" fill="#f0c9a5"/><path d="M335 250q115-190 230 0v-65q-115-105-230 0z" fill="#6a4a38"/><rect x="300" y="365" width="300" height="230" rx="100" fill="${accent}"/><circle cx="415" cy="255" r="10" fill="#40352f"/><circle cx="485" cy="255" r="10" fill="#40352f"/><path d="M415 310q35 25 70 0" fill="none" stroke="#8a5d4d" stroke-width="8" stroke-linecap="round"/><rect x="125" y="565" width="650" height="78" rx="28" fill="#fff" opacity=".88"/><text x="450" y="615" text-anchor="middle" font-family="Arial,sans-serif" font-size="34" fill="#554d47">${label}</text></svg>`}
function blob(i){return new Blob([svgPhoto(i)],{type:'image/svg+xml'})}
async function resetSample(){const year=await ensureInitialSchoolYear(),students=await getAll(STORES.students),moments=await getAll(STORES.moments),photos=await getAll(STORES.photos),enrollments=await getAll(STORES.enrollments);for(const m of moments.filter(x=>x.demoStudentId===SID||(x.studentIds||[]).includes(SID)))await remove(STORES.moments,m.id);for(const p of photos.filter(x=>String(x.id).startsWith('lm-demo-photo-')))await remove(STORES.photos,p.id);for(const e of enrollments.filter(x=>x.studentId===SID))await remove(STORES.enrollments,e.id);if(students.some(x=>x.id===SID))await remove(STORES.students,SID);await put(STORES.students,{id:SID,name:'Avery — Sample Student',isDemo:true,createdAt:new Date().toISOString()});await put(STORES.enrollments,{id:`${SID}-${year.id}`,studentId:SID,schoolYearId:year.id,active:true,createdAt:new Date().toISOString()});for(let i=0;i<16;i++){const photoId=`lm-demo-photo-${i+1}`,momentId=`lm-demo-moment-${i+1}`,d=new Date(2026,7,18+i*9);await put(STORES.photos,{id:photoId,blob:blob(i),name:`Avery sample ${i+1}.svg`,size:svgPhoto(i).length,type:'image/svg+xml',createdAt:d.toISOString()});await put(STORES.moments,{id:momentId,demoStudentId:SID,schoolYearId:year.id,studentIds:[SID],photoId,date:d.toISOString().slice(0,10),createdAt:d.toISOString(),caption:CAPTIONS[i],tags:TAGS[i],favorite:i%5===0})}alert('Sample Student Avery is ready with 16 portfolio Moments ♡');location.reload()}
function install(){const screen=app.querySelector('.class-manager-screen');if(!screen||screen.querySelector('#lm-sample-student'))return;const btn=document.createElement('button');btn.type='button';btn.id='lm-sample-student';btn.className='secondary';btn.style.cssText='width:100%;margin:12px 0';btn.textContent='♡ Create / Reset Sample Student';btn.onclick=()=>{if(confirm('Create or reset Avery, the sample student, with 16 demo Moments for portfolio testing?'))resetSample().catch(e=>alert(`Could not create sample student: ${e.message||e}`))};const target=screen.querySelector('#school-year')?.parentElement||screen.querySelector('.header-title');target?.insertAdjacentElement('afterend',btn)}
new MutationObserver(install).observe(app,{childList:true,subtree:true});install();