import {getAll,put,clearStore,STORES} from './db.js';
const app=document.querySelector('#app');
const STORE_NAMES=Object.values(STORES);

function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(r.error);r.onload=()=>resolve(r.result);r.readAsDataURL(blob)})}
function dataURLToBlob(dataUrl){const [head,body]=String(dataUrl).split(',');const mime=(head.match(/data:([^;]+)/)||[])[1]||'application/octet-stream';const bin=atob(body||'');const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime})}
async function serializeRecord(record){const out={...record};for(const [k,v] of Object.entries(out)){if(v instanceof Blob)out[k]={__lmBlob:true,data:await blobToDataURL(v)}}return out}
function reviveRecord(record){const out={...record};for(const [k,v] of Object.entries(out)){if(v&&typeof v==='object'&&v.__lmBlob&&v.data)out[k]=dataURLToBlob(v.data)}return out}
async function buildBackup(){const stores={};for(const name of STORE_NAMES){const rows=await getAll(name);stores[name]=[];for(const row of rows)stores[name].push(await serializeRecord(row))}return {format:'little-moments-backup',version:1,createdAt:new Date().toISOString(),stores}}
async function downloadBackup(status){try{status.textContent='Preparing your backup…';const backup=await buildBackup();const blob=new Blob([JSON.stringify(backup)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;const d=new Date();const stamp=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;a.download=`Little-Moments-Backup-${stamp}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);status.textContent='Backup created ♡ Keep that file somewhere safe.'}catch(err){console.error(err);status.textContent='The backup could not be created.'}}
async function restoreBackup(file,status){try{status.textContent='Checking backup…';const data=JSON.parse(await file.text());if(data?.format!=='little-moments-backup'||!data.stores)throw new Error('Invalid backup');if(!confirm('Restore this Little Moments backup? This will replace the data currently saved on this device.')){status.textContent='Restore canceled.';return}status.textContent='Restoring your memories…';for(const name of STORE_NAMES)await clearStore(name);for(const name of STORE_NAMES){const rows=Array.isArray(data.stores[name])?data.stores[name]:[];for(const row of rows)await put(name,reviveRecord(row))}status.textContent='Restore complete ♡ Reloading Little Moments…';setTimeout(()=>location.reload(),700)}catch(err){console.error(err);status.textContent='That file is not a valid Little Moments backup.'}}

function openSettings(){app.innerHTML=`<section class="screen settings-screen"><header class="header"><button class="icon-btn" id="settings-back">←</button><div class="header-title"><small>Little Moments</small><h2>Settings &amp;<br>Data Safety</h2></div><button class="icon-btn" aria-label="Data safety information">♡</button></header><div class="settings-intro">the quiet little things that help keep every memory safe ♡</div><div class="settings-list"><section class="settings-card"><div class="settings-card-head"><div class="settings-card-icon">♡</div><div><h3>Privacy</h3><p>Little Moments keeps classroom information inside this app on your device.</p></div></div><div class="settings-status"><span>Your classroom memories stay private.</span><span class="settings-pill">Local</span></div></section><section class="settings-card"><div class="settings-card-head"><div class="settings-card-icon">↥</div><div><h3>Backup &amp; Restore</h3><p>Create a safe copy of your class, moments, photos, and portfolios for another device or school year.</p></div></div><div class="backup-actions"><button class="primary compact" id="create-backup">Create Backup</button><button class="secondary compact" id="restore-backup">Restore Backup</button><input id="restore-file" class="sr-only" type="file" accept="application/json,.json"></div><div class="settings-status"><span id="backup-status">Your backup includes photos and student profiles.</span><span class="settings-pill">Ready</span></div></section><section class="settings-card"><div class="settings-card-head"><div class="settings-card-icon">▣</div><div><h3>Storage</h3><p>See how much space your saved photos and Little Moments are using.</p></div></div><div class="settings-status"><span>Storage details will appear here.</span><span class="settings-pill soon">Coming next</span></div></section><section class="settings-card"><div class="settings-card-head"><div class="settings-card-icon">✦</div><div><h3>Preferences</h3><p>App choices such as display and journal preferences will live here as we add them.</p></div></div><div class="settings-status"><span>Nothing here changes your saved memories.</span><span class="settings-pill soon">Coming next</span></div></section></div><div class="settings-note">Your students, school years, and saved Little Moments stay connected unless you deliberately change or remove them. ♡</div></section>`;app.querySelector('#settings-back').addEventListener('click',()=>location.reload());const status=app.querySelector('#backup-status'),fileInput=app.querySelector('#restore-file');app.querySelector('#create-backup').addEventListener('click',()=>downloadBackup(status));app.querySelector('#restore-backup').addEventListener('click',()=>fileInput.click());fileInput.addEventListener('change',()=>{const file=fileInput.files?.[0];if(file)restoreBackup(file,status)});window.scrollTo({top:0,behavior:'instant'})}

document.addEventListener('click',e=>{const btn=e.target.closest('#settings');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();openSettings()},true);
document.addEventListener('click',e=>{if(e.target.closest('#settings'))e.stopImmediatePropagation()},false);
